backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "presentations"
    label: "Presentations"
    folder: "presentations"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Upload PPT", name: "file", widget: "file" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
